theme: minima
title: MeLeMa Blogs
author: Nexxus-LMT
email: bellotd*****@*.com
description: > # this means to ignore newlines until "baseurl:"
  Beginnings of a small island empire...Journey to succes or mission to failure? See how MeLeMa will grow from here.

# social links
twitter_username: Should I make 1? # DO NOT include the @ character, or else the build will fail!
github_username:  Nexxux-LMT # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
